-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/combFilterFeedforward/combFilterSystem.vhd
-- Created: 2024-03-20 10:34:09
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1.01725e-08
-- Target subsystem base rate: 1.01725e-08
-- Explicit user oversample request: 2048x
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.08333e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- audioOut                      ce_out        2.08333e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: combFilterSystem
-- Source Path: combFilterFeedforward/combFilterSystem
-- Hierarchy Level: 0
-- Model version: 6.4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY combFilterSystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        audioIn                           :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        delayM                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        b0                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En16
        bM                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En16
        wetDryMix                         :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        ce_out                            :   OUT   std_logic;
        audioOut                          :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En23
        );
END combFilterSystem;


ARCHITECTURE rtl OF combFilterSystem IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT combFilterSystem_tc
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          enb                             :   OUT   std_logic;
          enb_1_2048_0                    :   OUT   std_logic;
          enb_1_2048_1                    :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT combFilterFeedforward
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_1                    :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          audioIn                         :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
          delayM                          :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          b0                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En16
          bM                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En16
          audioOut                        :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En23
          );
  END COMPONENT;

  COMPONENT wetDryMixer
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dryAudio                        :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
          wetAudio                        :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
          wetDryMix                       :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
          audioOut                        :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En23
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : combFilterSystem_tc
    USE ENTITY work.combFilterSystem_tc(rtl);

  FOR ALL : combFilterFeedforward
    USE ENTITY work.combFilterFeedforward(rtl);

  FOR ALL : wetDryMixer
    USE ENTITY work.wetDryMixer(rtl);

  -- Signals
  SIGNAL enb_1_2048_1                     : std_logic;
  SIGNAL enb                              : std_logic;
  SIGNAL enb_1_2048_0                     : std_logic;
  SIGNAL audioIn_1                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL combFilterFeedforward_out1       : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL wetDryMix_1                      : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL wetDryMixer_out1                 : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL wetDryMixer_out1_signed          : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL t_bypass_reg                     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL wetDryMixer_out1_1               : signed(23 DOWNTO 0);  -- sfix24_En23

BEGIN
  -- 
  -- Dry signal = unprocessed (raw) signal
  -- Wet signal = processed signal
  -- 
  -- wetDryMix = ratio of wet to dry signals
  -- wetDryMix = 1     (audioOut = all Wet)
  -- wetDryMix = 0     (audioOut = all Dry)
  -- wetDryMix = 0.5  (audioOut = 50/50 Wet/Dry)

  u_combFilterSystem_tc : combFilterSystem_tc
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              enb => enb,
              enb_1_2048_0 => enb_1_2048_0,
              enb_1_2048_1 => enb_1_2048_1
              );

  u_combFilterFeedforward : combFilterFeedforward
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_1 => enb_1_2048_1,
              enb => enb,
              enb_1_2048_0 => enb_1_2048_0,
              audioIn => audioIn,  -- sfix24_En23
              delayM => delayM,  -- uint16
              b0 => b0,  -- sfix16_En16
              bM => bM,  -- sfix16_En16
              audioOut => combFilterFeedforward_out1  -- sfix24_En23
              );

  u_wetDryMixer : wetDryMixer
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dryAudio => audioIn_1,  -- sfix24_En23
              wetAudio => combFilterFeedforward_out1,  -- sfix24_En23
              wetDryMix => wetDryMix_1,  -- ufix16_En16
              audioOut => wetDryMixer_out1  -- sfix24_En23
              );

  audioIn_1 <= std_logic_vector(signed(audioIn));

  wetDryMix_1 <= std_logic_vector(unsigned(wetDryMix));

  wetDryMixer_out1_signed <= signed(wetDryMixer_out1);

  t_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      t_bypass_reg <= to_signed(16#000000#, 24);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_1 = '1' THEN
        t_bypass_reg <= wetDryMixer_out1_signed;
      END IF;
    END IF;
  END PROCESS t_bypass_process;

  
  wetDryMixer_out1_1 <= wetDryMixer_out1_signed WHEN enb_1_2048_1 = '1' ELSE
      t_bypass_reg;

  audioOut <= std_logic_vector(wetDryMixer_out1_1);

  ce_out <= enb_1_2048_1;

END rtl;

