-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/fftAnalysisSynthesis/analysis.vhd
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: analysis
-- Source Path: fftAnalysisSynthesis/fftAnalysisSynthesis/analysis
-- Hierarchy Level: 1
-- Model version: 8.2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY analysis IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        enb_1_2048_1                      :   IN    std_logic;
        enb                               :   IN    std_logic;
        enb_1_4194304_1                   :   IN    std_logic;
        enb_1_4194304_0                   :   IN    std_logic;
        audioIn                           :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        passthrough                       :   IN    std_logic;  -- ufix1
        filterSelect                      :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        fftData_re                        :   OUT   std_logic_vector(30 DOWNTO 0);  -- sfix31_En23
        fftData_im                        :   OUT   std_logic_vector(30 DOWNTO 0);  -- sfix31_En23
        fftValid                          :   OUT   std_logic;
        fftFramePulse                     :   OUT   std_logic;
        passthroughFast                   :   OUT   std_logic;  -- ufix1
        filterSelectFast                  :   OUT   std_logic_vector(1 DOWNTO 0)  -- ufix2
        );
END analysis;


ARCHITECTURE rtl OF analysis IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT fftFrameBuffering
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          enb_1_2048_1                    :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_4194304_1                 :   IN    std_logic;
          enb_1_4194304_0                 :   IN    std_logic;
          audioIn                         :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
          passthrough                     :   IN    std_logic;  -- ufix1
          filterSelect                    :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          fftData                         :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
          fftDataValid                    :   OUT   std_logic;
          startPulseFast                  :   OUT   std_logic;
          passthroughFast                 :   OUT   std_logic;  -- ufix1
          filterSelectFast                :   OUT   std_logic_vector(1 DOWNTO 0)  -- ufix2
          );
  END COMPONENT;

  COMPONENT FFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(30 DOWNTO 0);  -- sfix31_En23
          dataOut_im                      :   OUT   std_logic_vector(30 DOWNTO 0);  -- sfix31_En23
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : fftFrameBuffering
    USE ENTITY work.fftFrameBuffering(rtl);

  FOR ALL : FFT
    USE ENTITY work.FFT(rtl);

  -- Signals
  SIGNAL fftFrameBuffering_out1           : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL fftValid_1                       : std_logic;
  SIGNAL fftFrameBuffering_out3           : std_logic;
  SIGNAL fftFrameBuffering_out4           : std_logic;  -- ufix1
  SIGNAL fftFrameBuffering_out5           : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL fftValid_2                       : std_logic;
  SIGNAL FFT_out1_re                      : std_logic_vector(30 DOWNTO 0);  -- ufix31
  SIGNAL FFT_out1_im                      : std_logic_vector(30 DOWNTO 0);  -- ufix31
  SIGNAL FFT_out2                         : std_logic;

BEGIN
  -- The ready signal is ignored by design
  -- since data won't be sent while FFT
  -- engine is busy.

  u_fftFrameBuffering : fftFrameBuffering
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              enb_1_2048_1 => enb_1_2048_1,
              enb => enb,
              enb_1_4194304_1 => enb_1_4194304_1,
              enb_1_4194304_0 => enb_1_4194304_0,
              audioIn => audioIn,  -- sfix24_En23
              passthrough => passthrough,  -- ufix1
              filterSelect => filterSelect,  -- ufix2
              fftData => fftFrameBuffering_out1,  -- sfix24_En23
              fftDataValid => fftValid_1,
              startPulseFast => fftFrameBuffering_out3,
              passthroughFast => fftFrameBuffering_out4,  -- ufix1
              filterSelectFast => fftFrameBuffering_out5  -- ufix2
              );

  u_FFT : FFT
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              dataIn => fftFrameBuffering_out1,  -- sfix24_En23
              validIn => fftValid_2,
              dataOut_re => FFT_out1_re,  -- sfix31_En23
              dataOut_im => FFT_out1_im,  -- sfix31_En23
              validOut => FFT_out2
              );

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      fftValid_2 <= '0';
    ELSIF rising_edge(clk) THEN
      IF enb_1_2048_0 = '1' THEN
        fftValid_2 <= fftValid_1;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  fftData_re <= FFT_out1_re;

  fftData_im <= FFT_out1_im;

  fftValid <= FFT_out2;

  fftFramePulse <= fftFrameBuffering_out3;

  passthroughFast <= fftFrameBuffering_out4;

  filterSelectFast <= fftFrameBuffering_out5;

END rtl;

