-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/fftAnalysisSynthesis/applyComplexGains.vhd
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: applyComplexGains
-- Source Path: fftAnalysisSynthesis/fftAnalysisSynthesis/frequencyDomainProcessing/applyComplexGains
-- Hierarchy Level: 2
-- Model version: 8.3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.fftAnalysisSynthesis_pkg.ALL;

ENTITY applyComplexGains IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        fftData_re                        :   IN    std_logic_vector(30 DOWNTO 0);  -- sfix31_En23
        fftData_im                        :   IN    std_logic_vector(30 DOWNTO 0);  -- sfix31_En23
        fftValid                          :   IN    std_logic;
        fftFramePulse                     :   IN    std_logic;
        filterSelect                      :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        fftModifiedData_re                :   OUT   std_logic_vector(30 DOWNTO 0);  -- sfix31_En23
        fftModifiedData_im                :   OUT   std_logic_vector(30 DOWNTO 0);  -- sfix31_En23
        fftValidOut                       :   OUT   std_logic;
        fftFramePulseOut                  :   OUT   std_logic
        );
END applyComplexGains;


ARCHITECTURE rtl OF applyComplexGains IS

  -- Component Declarations
  COMPONENT fftFilterCoefficients
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          filterSelect                    :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          fftValid                        :   IN    std_logic;
          filterCoefficients_re           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          filterCoefficients_im           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : fftFilterCoefficients
    USE ENTITY work.fftFilterCoefficients(rtl);

  -- Signals
  SIGNAL fftData_re_signed                : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL fftData_im_signed                : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL fftData_re_1                     : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL fftData_im_1                     : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL HwModeRegister_reg               : vector_of_signed31(0 TO 1);  -- sfix31 [2]
  SIGNAL Product_C2ReIm_1_C2ReIm_A        : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL fftFilterCoefficients_out1_re    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL fftFilterCoefficients_out1_im    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL fftFilterCoefficients_out1_re_signed : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL fftFilterCoefficients_out1_im_signed : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product_C2ReIm_2_C2ReIm_A        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product_mul_temp                 : signed(46 DOWNTO 0);  -- sfix47_En31
  SIGNAL Product_Re_AC                    : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL Product_Re_AC_1                  : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL HwModeRegister4_reg              : vector_of_signed31(0 TO 1);  -- sfix31 [2]
  SIGNAL Product_C2ReIm_1_C2ReIm_B        : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL Product_C2ReIm_2_C2ReIm_B        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Product2_mul_temp                : signed(46 DOWNTO 0);  -- sfix47_En31
  SIGNAL Product_Re_BD                    : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL Product_Re_BD_1                  : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL mulOutput                        : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL HwModeRegister2_reg              : vector_of_signed31(0 TO 1);  -- sfix31 [2]
  SIGNAL Product_C2ReIm_1_C2ReIm_A_1      : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL Product1_mul_temp                : signed(46 DOWNTO 0);  -- sfix47_En31
  SIGNAL Product_Im_AD                    : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL Product_Im_AD_1                  : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL HwModeRegister6_reg              : vector_of_signed31(0 TO 1);  -- sfix31 [2]
  SIGNAL Product_C2ReIm_1_C2ReIm_B_1      : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL Product3_mul_temp                : signed(46 DOWNTO 0);  -- sfix47_En31
  SIGNAL Product_Im_BC                    : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL Product_Im_BC_1                  : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL mulOutput_1                      : signed(30 DOWNTO 0);  -- sfix31_En23
  SIGNAL fftFramePulse_1                  : std_logic;

  ATTRIBUTE multstyle : string;

BEGIN
  -- Output data type is inherited
  -- from the first input.
  -- The frame pulse needs to be delayed 
  -- to complensate for the latency 
  -- of the Filter Coefficent block.
  -- The valid needs to be delayed
  -- to complensate for the latency 
  -- of the Filter Coefficent block.
  -- Data needs to be delayed
  -- to complensate for the latency 
  -- of the Filter Coefficent block.

  u_fftFilterCoefficients : fftFilterCoefficients
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              filterSelect => filterSelect,  -- ufix2
              fftValid => fftValid,
              filterCoefficients_re => fftFilterCoefficients_out1_re,  -- sfix16_En8
              filterCoefficients_im => fftFilterCoefficients_out1_im  -- sfix16_En8
              );

  fftData_re_signed <= signed(fftData_re);

  fftData_im_signed <= signed(fftData_im);

  rd_0_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      fftData_re_1 <= to_signed(16#00000000#, 31);
      fftData_im_1 <= to_signed(16#00000000#, 31);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        fftData_re_1 <= fftData_re_signed;
        fftData_im_1 <= fftData_im_signed;
      END IF;
    END IF;
  END PROCESS rd_0_process;


  HwModeRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HwModeRegister_reg <= (OTHERS => to_signed(16#00000000#, 31));
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        HwModeRegister_reg(0) <= fftData_re_1;
        HwModeRegister_reg(1) <= HwModeRegister_reg(0);
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;

  Product_C2ReIm_1_C2ReIm_A <= HwModeRegister_reg(1);

  fftFilterCoefficients_out1_re_signed <= signed(fftFilterCoefficients_out1_re);

  reduced_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Product_C2ReIm_2_C2ReIm_A <= to_signed(16#0000#, 16);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Product_C2ReIm_2_C2ReIm_A <= fftFilterCoefficients_out1_re_signed;
      END IF;
    END IF;
  END PROCESS reduced_process;


  Product_mul_temp <= Product_C2ReIm_1_C2ReIm_A * Product_C2ReIm_2_C2ReIm_A;
  Product_Re_AC <= Product_mul_temp(38 DOWNTO 8);

  PipelineRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Product_Re_AC_1 <= to_signed(16#00000000#, 31);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Product_Re_AC_1 <= Product_Re_AC;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  HwModeRegister4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HwModeRegister4_reg <= (OTHERS => to_signed(16#00000000#, 31));
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        HwModeRegister4_reg(0) <= fftData_im_1;
        HwModeRegister4_reg(1) <= HwModeRegister4_reg(0);
      END IF;
    END IF;
  END PROCESS HwModeRegister4_process;

  Product_C2ReIm_1_C2ReIm_B <= HwModeRegister4_reg(1);

  fftFilterCoefficients_out1_im_signed <= signed(fftFilterCoefficients_out1_im);

  reduced_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Product_C2ReIm_2_C2ReIm_B <= to_signed(16#0000#, 16);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Product_C2ReIm_2_C2ReIm_B <= fftFilterCoefficients_out1_im_signed;
      END IF;
    END IF;
  END PROCESS reduced_1_process;


  Product2_mul_temp <= Product_C2ReIm_1_C2ReIm_B * Product_C2ReIm_2_C2ReIm_B;
  Product_Re_BD <= Product2_mul_temp(38 DOWNTO 8);

  PipelineRegister2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Product_Re_BD_1 <= to_signed(16#00000000#, 31);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Product_Re_BD_1 <= Product_Re_BD;
      END IF;
    END IF;
  END PROCESS PipelineRegister2_process;


  mulOutput <= Product_Re_AC_1 - Product_Re_BD_1;

  fftModifiedData_re <= std_logic_vector(mulOutput);

  HwModeRegister2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HwModeRegister2_reg <= (OTHERS => to_signed(16#00000000#, 31));
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        HwModeRegister2_reg(0) <= fftData_re_1;
        HwModeRegister2_reg(1) <= HwModeRegister2_reg(0);
      END IF;
    END IF;
  END PROCESS HwModeRegister2_process;

  Product_C2ReIm_1_C2ReIm_A_1 <= HwModeRegister2_reg(1);

  Product1_mul_temp <= Product_C2ReIm_1_C2ReIm_A_1 * Product_C2ReIm_2_C2ReIm_B;
  Product_Im_AD <= Product1_mul_temp(38 DOWNTO 8);

  PipelineRegister1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Product_Im_AD_1 <= to_signed(16#00000000#, 31);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Product_Im_AD_1 <= Product_Im_AD;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  HwModeRegister6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HwModeRegister6_reg <= (OTHERS => to_signed(16#00000000#, 31));
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        HwModeRegister6_reg(0) <= fftData_im_1;
        HwModeRegister6_reg(1) <= HwModeRegister6_reg(0);
      END IF;
    END IF;
  END PROCESS HwModeRegister6_process;

  Product_C2ReIm_1_C2ReIm_B_1 <= HwModeRegister6_reg(1);

  Product3_mul_temp <= Product_C2ReIm_1_C2ReIm_B_1 * Product_C2ReIm_2_C2ReIm_A;
  Product_Im_BC <= Product3_mul_temp(38 DOWNTO 8);

  PipelineRegister3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Product_Im_BC_1 <= to_signed(16#00000000#, 31);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Product_Im_BC_1 <= Product_Im_BC;
      END IF;
    END IF;
  END PROCESS PipelineRegister3_process;


  mulOutput_1 <= Product_Im_AD_1 + Product_Im_BC_1;

  fftModifiedData_im <= std_logic_vector(mulOutput_1);

  rd_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      fftFramePulse_1 <= '0';
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        fftFramePulse_1 <= fftFramePulse;
      END IF;
    END IF;
  END PROCESS rd_5_process;


  fftValidOut <= fftValid;

  fftFramePulseOut <= fftFramePulse_1;

END rtl;

