-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/fftAnalysisSynthesis/fifoWriteSelect.vhd
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fifoWriteSelect
-- Source Path: fftAnalysisSynthesis/fftAnalysisSynthesis/synthesis/overlapAdd/fifoWriteSelect
-- Hierarchy Level: 3
-- Model version: 8.2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fifoWriteSelect IS
  PORT( fifoCounter                       :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        validSignal                       :   IN    std_logic;
        valid1                            :   OUT   std_logic;
        valid2                            :   OUT   std_logic;
        valid3                            :   OUT   std_logic;
        valid4                            :   OUT   std_logic
        );
END fifoWriteSelect;


ARCHITECTURE rtl OF fifoWriteSelect IS

  ATTRIBUTE multstyle : string;

  -- Signals
  SIGNAL fifoCounter_unsigned             : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  fifoCounter_unsigned <= unsigned(fifoCounter);

  fifoWriteSelect_1_output : PROCESS (fifoCounter_unsigned, validSignal)
  BEGIN
    --MATLAB Function 'fftAnalysisSynthesis/synthesis/overlapAdd/fifoWriteSelect'
    CASE fifoCounter_unsigned IS
      WHEN "00" =>
        valid1 <= validSignal;
        valid2 <= '0';
        valid3 <= '0';
        valid4 <= '0';
      WHEN "01" =>
        valid1 <= '0';
        valid2 <= validSignal;
        valid3 <= '0';
        valid4 <= '0';
      WHEN "10" =>
        valid1 <= '0';
        valid2 <= '0';
        valid3 <= validSignal;
        valid4 <= '0';
      WHEN "11" =>
        valid1 <= '0';
        valid2 <= '0';
        valid3 <= '0';
        valid4 <= validSignal;
      WHEN OTHERS => 
        valid1 <= '0';
        valid2 <= '0';
        valid3 <= '0';
        valid4 <= '0';
    END CASE;
  END PROCESS fifoWriteSelect_1_output;


END rtl;

